### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by wushupei1997** [BADBADBADBOY/pytorch.ctpn#10]
模型训练貌似很正常，loss都在正常下降，如图：
![image](https://user-images.githubusercontent.com/57393009/83585572-c4880e00-a57c-11ea-89d7-eb04d02925f4.png)
d但是我在测试图片的时候，最终没有得到任何结果，字符所在位置矩形框为空，想请教一下题主，这是什么原因，我用的还是训练集的图片进行测试的/(ㄒoㄒ)/~~

**Comment by fxwfzsxyq** [comment]
> 模型训练貌似很正常，loss都在正常下降，如图：
> ![image](https://user-images.githubusercontent.com/57393009/83585572-c4880e00-a57c-11ea-89d7-eb04d02925f4.png)
> d但是我在测试图片的时候，最终没有得到任何结果，字符所在位置矩形框为空，想请教一下题主，这是什么原因，我用的还是训练集的图片进行测试的/(ㄒoㄒ)/~~

你这个训练了多少epoch ，一般在20epoch之后在测试，越轻量化的模型越要训练久一点，因为可能你的分类分数达不到阈值，或者你
https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/utils/text_connector/text_connect_cfg.py  改小TEXT_PROPOSALS_MIN_SCORE 和 LINE_MIN_SCORE 看看

**Comment by fxwfzsxyq** [comment]
还有我建议先下载我的模型测试一下，排除代码问题

**Comment by wushupei1997** [comment]
模型是下载你的，只不过数据是用自己的，我的数据大概有3w，所以epoch就设置的比较小；还有TEXT_PROPOSALS_MIN_SCORE和LINE_MIN_SCORE这两个参数是自己调参的吗？题主你训练的loss最后达到了多少才有那种效果？还有一个问题，detect_type = 'O' # 'O' or 'H'，这两个设定是什么意思？

**Comment by fxwfzsxyq** [comment]
> 模型是下载你的，只不过数据是用自己的，我的数据大概有3w，所以epoch就设置的比较小；还有TEXT_PROPOSALS_MIN_SCORE和LINE_MIN_SCORE这两个参数是自己调参的吗？题主你训练的loss最后达到了多少才有那种效果？还有一个问题，detect_type = 'O' # 'O' or 'H'，这两个设定是什么意思？

这两个是模型训练完测试时候的参数，TEXT_PROPOSALS_MIN_SCORE是指anchor的分数阈值，LINE_MIN_SCORE是指将anchor连成一行的阈值，低于这些阈值的框都会被过滤掉，因为你训练时间太短了，导致阈值不满足全被过滤了，自然就没有框， 一般总loss会下降到10的-2级，不同数据集不太一样， O和H连接auchor方式不一样，简单来说，O出来的文字框可以是倾斜的，H出来的是水平的

**Comment by fxwfzsxyq** [comment]
还有我的意思是说用我的模型测试一下你的数据看看检测效果如何

**Comment by wushupei1997** [comment]
貌似那个预训练模型文件有点损坏，无法解压

**Comment by wushupei1997** [comment]
题主方便把文件从邮箱发给我吗？🙏，wushupei1997@163.com

**Comment by fxwfzsxyq** [comment]
> 题主方便把文件从邮箱发给我吗？🙏，[wushupei1997@163.com](mailto:wushupei1997@163.com)

我现在发不了，等晚上吧，这个模型不用解压，你下载一个小的模型先试试看，应该都是可以下载的

**Comment by wushupei1997** [comment]
好的，太感谢题主了，帮了这么多，新手第一次做检测，太难了😭

**Comment by BADBADBADBOY** [comment]
> > 题主方便把文件从邮箱发给我吗？🙏，[wushupei1997@163.com](mailto:wushupei1997@163.com)
> 
> 我现在发不了，等晚上吧，这个模型不用解压，你下载一个小的模型先试试看，应该都是可以下载的

发了轻量的模型，其他模型太大了

**Comment by wushupei1997** [comment]
收到了，感谢感谢！！
