### ISSUE TITLE
train  error

### ISSUE THREAD

**Issue by zgd716** [BADBADBADBOY/pytorch.ctpn#11]
RuntimeError: stack expects each tensor to be equal size, but got [3, 768, 768] at entry 0 and [3, 784, 784] at entry 1

**Comment by BADBADBADBOY** [comment]
> RuntimeError: stack expects each tensor to be equal size, but got [3, 768, 768] at entry 0 and [3, 784, 784] at entry 1

你训练的命令用的啥

**Comment by zgd716** [comment]
python train.py --base_model vgg16_bn --batch_size 4

**Comment by zgd716** [comment]
请问一下:你训练的代码支持images是各种不同尺寸的吗?

**Comment by BADBADBADBOY** [comment]
> RuntimeError: stack expects each tensor to be equal size, but got [3, 768, 768] at entry 0 and [3, 784, 784] at entry 1

你训练的命令用的啥

> 请问一下:你训练的代码支持images是各种不同尺寸的吗?

https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/dataLoader/shrinkbox.py ，第23，24改成
new_h = np.round(img_size[0] * im_scale).astype(np.int)
new_w = np.round(img_size[1] * im_scale).astype(np.int)

**Comment by zgd716** [comment]
> > RuntimeError: stack expects each tensor to be equal size, but got [3, 768, 768] at entry 0 and [3, 784, 784] at entry 1
> 
> 你训练的命令用的啥
> 
> > 请问一下:你训练的代码支持images是各种不同尺寸的吗?
> 
> https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/dataLoader/shrinkbox.py ，第23，24改成
> new_h = np.round(img_size[0] * im_scale).astype(np.int)
> new_w = np.round(img_size[1] * im_scale).astype(np.int)
还是不行,还是一样的错误,images中好像图片尺寸不一致,会有这样的问题

**Comment by BADBADBADBOY** [comment]
> > > RuntimeError: stack expects each tensor to be equal size, but got [3, 768, 768] at entry 0 and [3, 784, 784] at entry 1
> > 
> > 
> > 你训练的命令用的啥
> > > 请问一下:你训练的代码支持images是各种不同尺寸的吗?
> > 
> > 
> > https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/dataLoader/shrinkbox.py ，第23，24改成
> > new_h = np.round(img_size[0] * im_scale).astype(np.int)
> > new_w = np.round(img_size[1] * im_scale).astype(np.int)
> > 还是不行,还是一样的错误,images中好像图片尺寸不一致,会有这样的问题

不会吧，我这边测试下来没问题了，你训练图片多大的啊，我把图片random到各个尺寸，改了之后没有报错

**Comment by zgd716** [comment]
我是把所有图片resize固定的尺寸跑起来的，原来数据集尺寸不一致，跑几个batch_size就报错

**Comment by fxwfzsxyq** [comment]
> 我是把所有图片resize固定的尺寸跑起来的，原来数据集尺寸不一致，跑几个batch_size就报错

没法复现你的问题，如果你发现问题在哪，可以提个pr

**Comment by jihe08** [comment]
你好，我想问一下，这个项目的requirements是什么呢

**Comment by jihe08** [comment]
你好，我想问一下这个项目的requirements是什么呢

**Comment by fxwfzsxyq** [comment]
> 你好，我想问一下这个项目的requirements是什么呢

就一般的深度学习环境就可以吧，缺什么包 pip 一下 有问题可以贴出来

**Comment by jihe08** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/Home/aistudio/work/data/MTWI2018/image/'
我按照dataload中的根目录把数据放进去，然而告诉我找不到这个文件

**Comment by fxwfzsxyq** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/Home/aistudio/work/data/MTWI2018/image/'
> 我按照dataload中的根目录把数据放进去，然而告诉我找不到这个文件

https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/dataLoader/dataLoad.py  第一，确认23-25行 你的图片和gt路径是不是正确，第二，如果你的图片和gt文件名是icdar2015格式的，就需要注释104行打开103行
