### ISSUE TITLE
请问标签里面的label一项是不是没有用于训练？

### ISSUE THREAD

**Issue by unanan** [BADBADBADBOY/pytorch.ctpn#12]
请问标签里面的label一项是不是没有用于训练？
我找了一下好像没看到output里有识别文字的结果

**Comment by unanan** [comment]
我看到了[loss.py里面关于num_class](https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/models/loss.py#L114)是写死了的……
这个值能魔改成label的种类数么hhh…… 
因为我自己的数据集的字符类别也不是很多，不然我试一下吧
不知道ctpn的分类识别能力如何？我试一下在后面加点分类的网络……

**Comment by fxwfzsxyq** [comment]
> 请问标签里面的label一项是不是没有用于训练？
> 我找了一下好像没看到output里有识别文字的结果

是没有参与训练

**Comment by fxwfzsxyq** [comment]
> 我看到了[loss.py里面关于num_class](https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/models/loss.py#L114)是写死了的……
> 这个值能魔改成label的种类数么hhh……
> 因为我自己的数据集的字符类别也不是很多，不然我试一下吧
> 不知道ctpn的分类识别能力如何？我试一下在后面加点分类的网络……

ctpn是做文本检测，不是做识别的

**Comment by unanan** [comment]
> > 我看到了[loss.py里面关于num_class](https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/models/loss.py#L114)是写死了的……
> > 这个值能魔改成label的种类数么hhh……
> > 因为我自己的数据集的字符类别也不是很多，不然我试一下吧
> > 不知道ctpn的分类识别能力如何？我试一下在后面加点分类的网络……
> 
> ctpn是做文本检测，不是做识别的

好的 那我看看别的方法
