### ISSUE TITLE
训练loss不下降

### ISSUE THREAD

**Issue by qingqing625** [BADBADBADBOY/pytorch.ctpn#14]
第一次训练很正常，也可以检测出文本。换了base_model后，训练loss值一直不下降，使用的ICDAR2015训练集，loss大概保持在0.66左右。尝试过更改学习率、将base model换回vgg16、重新下载部署 各种方法，还是不行。想请教下，这可能是什么原因造成的，该怎么解决呢？

**Comment by fxwfzsxyq** [comment]
初始训练的时候loss有下降吗

**Comment by fxwfzsxyq** [comment]
> 第一次训练很正常，也可以检测出文本。换了base_model后，训练loss值一直不下降，使用的ICDAR2015训练集，loss大概保持在0.66左右。尝试过更改学习率、将base model换回vgg16、重新下载部署 各种方法，还是不行。想请教下，这可能是什么原因造成的，该怎么解决呢？

初始训练的时候loss有下降吗

**Comment by qingqing625** [comment]
有的，初始训练的时候一切正常

**Comment by fxwfzsxyq** [comment]
> 有的，初始训练的时候一切正常

你测试过吗，不能检测文本

**Comment by fxwfzsxyq** [comment]
> 有的，初始训练的时候一切正常

如果你没改过代码，数据格式正确，应该没什么问题的，可能轻量的backbone准确率会低一点，但是都可以检测出文本

**Comment by qingqing625** [comment]
测试过，可以检测，precision=51%，recall=30%，hmean=38%

**Comment by fxwfzsxyq** [comment]
> 测试过，可以检测，precision=51%，recall=30%，hmean=38%

那是没问题的，可能loss只能降到这样，测试大小可参考论文

**Comment by qingqing625** [comment]
第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。

**Comment by fxwfzsxyq** [comment]
> 第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。

如果数据没动过，改动过代码，建议重新下载搞，问题只能是你自己找了，我也不知道你那里弄得有问题

**Comment by fxwfzsxyq** [comment]
> 第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。

ctpn都是很老的算法了，建议换别的搞吧  https://github.com/BADBADBADBOY/pytorchOCR

**Comment by qingqing625** [comment]
> > 第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。
> 
> 如果数据没动过，改动过代码，建议重新下载搞，问题只能是你自己找了，我也不知道你那里弄得有问题

数据代码都没有更改，也重新下载试了，还是同样的问题，我也不知道是为什么。

**Comment by fxwfzsxyq** [comment]
> > > 第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。
> > 
> > 
> > 如果数据没动过，改动过代码，建议重新下载搞，问题只能是你自己找了，我也不知道你那里弄得有问题
> 
> 数据代码都没有更改，也重新下载试了，还是同样的问题，我也不知道是为什么。

这两次，你训练的epoch是相近的吗，loss下降正常吗

**Comment by qingqing625** [comment]
> > > > 第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。
> > > 
> > > 
> > > 如果数据没动过，改动过代码，建议重新下载搞，问题只能是你自己找了，我也不知道你那里弄得有问题
> > 
> > 
> > 数据代码都没有更改，也重新下载试了，还是同样的问题，我也不知道是为什么。
> 
> 这两次，你训练的epoch是相近的吗，loss下降正常吗

epoch都设置的100，第一次loss下降正常，第二次loss值不下降。

**Comment by fxwfzsxyq** [comment]
> > > > > 第一次训练basemodel用的vgg16没什么问题。换过basemodel后，loss不下降，同时也检测了，检测结果都是0，没有检测出任何文字。又将basemodel换回vgg16后，还是同样问题。
> > > > 
> > > > 
> > > > 如果数据没动过，改动过代码，建议重新下载搞，问题只能是你自己找了，我也不知道你那里弄得有问题
> > > 
> > > 
> > > 数据代码都没有更改，也重新下载试了，还是同样的问题，我也不知道是为什么。
> > 
> > 
> > 这两次，你训练的epoch是相近的吗，loss下降正常吗
> 
> epoch都设置的100，第一次loss下降正常，第二次loss值不下降。

那我也不知道了，一般来说是数据问题，你可以调试一下

**Comment by qingqing625** [comment]
好的，我再找找问题，非常感谢您的解答！
