### ISSUE TITLE
关于/anchor_target_layer.py函数的问题

### ISSUE THREAD

**Issue by csliuchang** [BADBADBADBOY/pytorch.ctpn#15]
你好，我将您的代码在MSRTD-500上实现，格式规范为{X1，Y1，X2，Y2，.....X4，Y4, class}，报错如下，IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed，报错的位置pytorch.ctpn/utils/rpn_msr/anchor_target_layer.py中 dontcareflag = gt_boxes[:,-1].reshape(-1)语句里面，我感觉是我数据本身的问题，你可以指导下吗。

**Comment by csliuchang** [comment]
i have solved problem,MSRA-TD500 have some label with noise（no data in GT）,thanks to your code !

**Comment by BADBADBADBOY** [comment]
> i have solved problem,MSRA-TD500 have some label with noise（no data in GT）,thanks to your code !

ok，今天周末有活动就没看GitHub
