### ISSUE TITLE
window训练测试

### ISSUE THREAD

**Issue by chuanfuye** [BADBADBADBOY/pytorch.ctpn#16]
您好，我首先按照README 里面
`
# setup
nms and bbox utils are written in cython, you have to build the library first.
```shell
cd utils/bbox
sh make.sh
`
操作，但是终端会提示
mv: cannot stat 'build/*/*.so': No such file or directory
之后我没有理会，开始执行train.py,
`Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from utils.rpn_msr.anchor_target_layer import anchor_target_layer
  File "D:\code\work_code\ocr.pytorch-master\train_code\train_ctpn\utils\rpn_msr\anchor_target_layer.py", line 5, in <module>
    from utils.bbox.bbox import bbox_overlaps
就是会出现没有找到utils.bbox.bbox这个模块，望指点，是不是在window平台不能编译呢
感谢

**Comment by fxwfzsxyq** [comment]
> 您好，我首先按照README 里面
> `
> 
> # setup
> nms and bbox utils are written in cython, you have to build the library first.
> 
> ```shell
> cd utils/bbox
> sh make.sh
> `
> 操作，但是终端会提示
> mv: cannot stat 'build/*/*.so': No such file or directory
> 之后我没有理会，开始执行train.py,
> `Traceback (most recent call last):
>   File "train.py", line 21, in <module>
>     from utils.rpn_msr.anchor_target_layer import anchor_target_layer
>   File "D:\code\work_code\ocr.pytorch-master\train_code\train_ctpn\utils\rpn_msr\anchor_target_layer.py", line 5, in <module>
>     from utils.bbox.bbox import bbox_overlaps
> 就是会出现没有找到utils.bbox.bbox这个模块，望指点，是不是在window平台不能编译呢
> 感谢
> ```

这是linux下面编译方式，windows可以参照
1. https://github.com/eragonruan/text-detection-ctpn/issues/264
2. https://blog.csdn.net/u010554381/article/details/86519960
