### ISSUE TITLE
input image size

### ISSUE THREAD

**Issue by cuongngm** [BADBADBADBOY/pytorch.ctpn#17]
can i config the image input size is rectangle (ex: (768, 1024) instead of square?

**Comment by BADBADBADBOY** [comment]
> can i config the image input size is rectangle (ex: (768, 1024) instead of square?

Here, through batch training, the long side of the picture will be resize to the specified size, and the short side will be padding. If your picture has the same size, it can be rectangular input, but you may need to modify the code, but I don't think it is necessary

**Comment by cuongngm** [comment]
tks your reply and your repo

**Comment by cuongngm** [comment]
The labels have 4 coordinates, Can it help me detect the lines text skew (example: 15 degree angle than horizontal)?

**Comment by fxwfzsxyq** [comment]
> The labels have 4 coordinates, Can it help me detect the lines text skew (example: 15 degree angle than horizontal)?

If you want to detect oblique text, you can set detect_type =‘o'  in inference.py, but ctpn works better in detecting horizontal text. If you want to detect oblique text, I suggest to refer to my project https://github.com/BADBADBADBOY/pytorchOCR.

**Comment by cuongngm** [comment]
many tks bro
