### ISSUE TITLE
显存问题

### ISSUE THREAD

**Issue by flying-cows** [BADBADBADBOY/pytorch.ctpn#18]
作者你好，我使用你的代码，大概训练到9epoch的时候会报显存溢出错误。作者使用显存是多大，方便说一下吗？

**Comment by fxwfzsxyq** [comment]
> 作者你好，我使用你的代码，大概训练到9epoch的时候会报显存溢出错误。作者使用显存是多大，方便说一下吗？

照理来说训练的时候，显存是稳定的，不应该会出现显存溢出，我用的是v100 16g的

**Comment by flying-cows** [comment]
我使用的是1080ti 可能还是我的问题吧。因为好多模型都是迭代到一定epoch都会报显存的问题。
