### ISSUE TITLE
shrinkbox.py 中resize_image()是不是有问题？

### ISSUE THREAD

**Issue by PhilCuriosity** [BADBADBADBOY/pytorch.ctpn#19]
您好，请问`new_h = new_h if new_h //16 == 0 else (new_h // 16 + 1) * 16`
这里是不是求余
`new_h = new_h if new_h % 16 == 0 else (new_h // 16 + 1) * 16`

**Comment by fxwfzsxyq** [comment]
> 您好，请问`new_h = new_h if new_h //16 == 0 else (new_h // 16 + 1) * 16`
> 这里是不是求余
> `new_h = new_h if new_h % 16 == 0 else (new_h // 16 + 1) * 16`

是的，写错了

**Comment by PhilCuriosity** [comment]
好的，谢谢你开源的项目！
