### ISSUE TITLE
您好，make.sh出校问题，生成不了那两个文件，您有那两个.so文件吗

### ISSUE THREAD

**Issue by zeng-cy** [BADBADBADBOY/pytorch.ctpn#21]

**Comment by BADBADBADBOY** [comment]
> _No description provided._

必须要自己编译 这个是根据你自身环境编译的

**Comment by zeng-cy** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月13日(星期三) 上午10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorch.ctpn] 您好，make.sh出校问题，生成不了那两个文件，您有那两个.so文件吗 (Issue #21)





  
未提供说明。
  
必须要自己编译 这个是根据你自身环境编译的
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息 ID：<BADBADBADBOY/pytorch 。ctpn/issues/21/1182708362 @ github 。com&gt;
