### ISSUE TITLE
Unable to download model from Baidu Yun

### ISSUE THREAD

**Issue by nelaturuharsha** [BADBADBADBOY/pytorch.ctpn#6]
Hey! Thank you for open-sourcing the project, I am based out of China and hence I am not able to download the pre-trained model from Baidu Yun. Could you please host it on Google Drive?

It would be amazing.

Thanks.

**Comment by fxwfzsxyq** [comment]
Okay, due to the Wuhan outbreak, the model will be uploaded later @SreeHarshaNelaturu

**Comment by fxwfzsxyq** [comment]
you can download the model from here @SreeHarshaNelaturu  https://github.com/fxwfzsxyq/ctpnModel

**Comment by nelaturuharsha** [comment]
Thank you!
