### ISSUE TITLE
看到你更新模型了，多了很多不同backbone的模型，轻型网络的性能怎么样？

### ISSUE THREAD

**Issue by CaiQiuYu** [BADBADBADBOY/pytorch.ctpn#7]
你有对比这些模型的性能嘛?

**Comment by fxwfzsxyq** [comment]
> 你有对比这些模型的性能嘛?

没有具体用数据集对比过指标，所以不知道差异具体是多少，从MTWI2018训练的效果来看，都还可以。

**Comment by CaiQiuYu** [comment]
> > 你有对比这些模型的性能嘛?
> 
> 没有具体用数据集对比过指标，所以不知道差异具体是多少，从MTWI2018训练的效果来看，都还可以。

感谢！我也训练看看你这个
