### ISSUE TITLE
請問baiduyun的base model要怎麼讀?

### ISSUE THREAD

**Issue by kaieason** [BADBADBADBOY/pytorch.ctpn#8]
您好，

train.py 有個參數--base_model 可以讀取model

但如果是想透過您提供的baiduyun的base model，應該要怎麼讀?

謝謝

**Comment by kaieason** [comment]
另外詢問這個版本是不是已經沒有做random_ctpn_rotate?

**Comment by fxwfzsxyq** [comment]
> 您好，
> 
> train.py 有個參數--base_model 可以讀取model
> 
> 但如果是想透過您提供的baiduyun的base model，應該要怎麼讀?
> 
> 謝謝

这个--base_model 是用来加载torch提供的预训练模型，你如果要训练你自己的模型，加载这个就行了，我给的是测试用的，如果你非要加载，可以在train.py 创建模型之后按照inference的方式加载一下就可以

**Comment by fxwfzsxyq** [comment]
> 另外詢問這個版本是不是已經沒有做random_ctpn_rotate?

ctpn本身就是对水平文本效果好，我觉得没必要就去掉了，而且上个版本有点问题，效果不太好，这个版本是我比较满意的

**Comment by kaieason** [comment]
@BADBADBADBOY 
您好，我想問我用你舊的版本訓練後的模型去預測，在框文字的時候比較能完整框住文字
但是用這個新的版本訓練，很容易文字左右兩側沒框到
請問這個部分有什麼可以改善?
謝謝

**Comment by fxwfzsxyq** [comment]
> @BADBADBADBOY
> 您好，我想問我用你舊的版本訓練後的模型去預測，在框文字的時候比較能完整框住文字
> 但是用這個新的版本訓練，很容易文字左右兩側沒框到
> 請問這個部分有什麼可以改善?
> 謝謝

我没有遇到过这种情况，如果按照我给的命令训练和脚本测试，效果应该应该挺好的，是水平文本没框全吗，能贴图看看吗

**Comment by kaieason** [comment]
[舊版本](https://imgur.com/NcgDPPg) 的圖片

[新版本](https://imgur.com/a/aIq7AJ2) 的圖片

舊版本可以完整框住，但新版本會斷框

**Comment by fxwfzsxyq** [comment]
> [舊版本](https://imgur.com/NcgDPPg) 的圖片
> 
> [新版本](https://imgur.com/a/aIq7AJ2) 的圖片
> 
> 舊版本可以完整框住，但新版本會斷框

你给的链接我无法访问，你可以试试训练久一点看看，但是一般说30个epoch应该收敛的很好了，或者你把图发我邮箱2441124901@qq.com,你这个问题我倒挺好奇的

**Comment by kaieason** [comment]
@fxwfzsxyq 
您可以收發gmail信件嗎，我已經發給您了，謝謝

**Comment by fxwfzsxyq** [comment]
邮件收到了，一个是我觉得你没拟合好，还有就是你可以测试的时候调大https://github.com/BADBADBADBOY/pytorch.ctpn/blob/master/utils/text_connector/text_connect_cfg.py 里的MAX_HORIZONTAL_GAP=50，还有我建议别加载我给的测试模型还是加载torch的预训练模型重新训练比较好

**Comment by kaieason** [comment]
@fxwfzsxyq 
新版本的部分我是讀你提供，去下載vgg16預訓練模型跑的
我這邊先加大MAX_HORIZONTAL_GAP去跑看看
結果出來我再跟您說，謝謝

**Comment by BADBADBADBOY** [comment]
> @fxwfzsxyq
> 新版本的部分我是讀你提供，去下載vgg16預訓練模型跑的
> 我這邊先加大MAX_HORIZONTAL_GAP去跑看看
> 結果出來我再跟您說，謝謝

我用我提供的模型测了下你给的图片，效果没问题啊，而且我还测的是mobilenet，虽然会断但是不会漏检，毕竟没训练过你的数据，你针对性训练效果肯定比我的要好的

**Comment by kaieason** [comment]
請問
你的 max_horizontal_gap是50嗎
那你learning rate設定多少呀
Resize 一樣是max 1200嗎
謝謝

**Comment by BADBADBADBOY** [comment]
> 請問
> 你的 max_horizontal_gap是50嗎
> 那你learning rate設定多少呀
> Resize 一樣是max 1200嗎
> 謝謝
max_horizontal_gap 是50，lr 0.001,训练max 1048 ，测试 1200

**Comment by kaieason** [comment]
好的謝謝，
另外詢問你
1. inference.py 的def rotate 是不是沒用到?
2. 你的程式有辦法計算mAP (mean Average Precision)嗎?

**Comment by BADBADBADBOY** [comment]
> 好的謝謝，
> 另外詢問你
> 
> 1. inference.py 的def rotate 是不是沒用到?
> 2. 你的程式有辦法計算mAP (mean Average Precision)嗎?

是没用到 ，cal_rescall里面用了icdar2015中的衡量方方式，计算了rescall，precision和hmean
